import "./globals.css";
import Navbar from "app/layout/Header/Navbar.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="satoshi px-[4.5rem]">
        {/* <ThirdwebProvider> */}
          <Navbar />
          {children}
        {/* </ThirdwebProvider> */}
      </body>
    </html>
  );
}
